### ISSUE TITLE
Cannot change date of delivery on admin grant after submission

### ISSUE THREAD

**Issue by tmesser** [ledgerleapllc/devxdao-frontend#44]
Expected:

All fields except Title should be modifiable by the OP until such time as the grant enters vote

Actual:

"When will this be delivered" is not modifiable.

Example: #468 in the portal: https://portal.devxdao.com/app/proposal/468

**Comment by ledgerleapllc** [comment]
Putting this into the pipeline

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-backend/commit/66ce1b927e31e16656de83171326931c995a8283
