### ISSUE TITLE
[Improvement] Make proposals link clickable 

### ISSUE THREAD

**Issue by KillianH** [ledgerleapllc/devxdao-frontend#66]
It would be a nice addition to have the different proposal lists to have clickable links.
Actually when we click on a item from the list it redirect directly to the proposal with the react router (I assume you use react). This behavior shouldn't change to keep the smooth navigation on the portal.

But it would be nice to add a link on those items to open multiple proposal in multiple tab while browsing the list.

https://portal.devxdao.com/app/discussions
https://portal.devxdao.com/app/votes
https://portal.devxdao.com/app/all-proposals

**Comment by ledgerleapllc** [comment]
Should be solved by memory system upgrade.
