### ISSUE TITLE
[BUG] OPs cannot change fund request and allocation after submission

### ISSUE THREAD

**Issue by tmesser** [ledgerleapllc/devxdao-frontend#69]
EXPECTED:

All fields should be editable and updatable by OPs while their grant proposals are in the DISCUSSION phase.

ACTUAL:

The "Grant Details" heading (including the questions "Please enter the total amount you are requesting as a grant:", "Will payments for this work be made to a entity such as your company or organization instead of to you personally?", and "Please select all planned uses for your grant funds. Select all that apply and enter the estimated portion of grant funds allocated for each. All totals must equal the upper amount") is not editable.

This has caused problems with a few grants, and is active in #317 right now. Prompt assistance is appreciated; if prompt assistance cannot be rendered, please alert Tim Messer so a work-around can be attempted.

**Comment by ledgerleap** [comment]
GP466

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/devxdao-frontend/commit/983f9e77ed5b22ab51df6c935c1422ef0e13a2b3
